export const INITIAL_DATA = {
  // step 1
  escal_status: "",
  escal_date: "",
  type: "",
  title: "",
  description: "",
  recurrence: false,
  descal_date: "",
  // step 2
  cust_group: null,
  cust_brand: null,
  other_brands: [],
  cust_impact: "",
  cons_impact: "",
  cust_escal_level: null,
  cust_locations: [],
  car_model: "",
  car_platform: "",
  affected_cars: 1,
  // step 3
  vt_orgunit: null,
  additional_orgunits: [],
  vt_product: "",
  vt_plant: "",
  vt_addplants: [],
  supplier: "",
  vqts_qn: "",
  affected_parts: 1,
  action_status: null,
  action_description: "",
  estimated_descal_date: "",
  vt_division: null,
  vt_segment: null,
  vt_subsegment: null,
  // step 4
  follow_action: "",
  follow_duedate: "",
  follow_responsible: "",
  follow_status: null,
};
