-- TABLES
DROP TABLE "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_COLORS";
DROP TABLE "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_LEVELS";
DROP TABLE "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_QCAMS";
DROP TABLE "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_ALLOCATION";


CREATE TABLE "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_COLORS" (
      "ID" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 10)
    , "LABEL" VARCHAR(10)
    , "VALUE" VARCHAR(10)
    , "EXPLANATION" VARCHAR(100)
);


CREATE TABLE "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_LEVELS" (
      "ID" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 10)
    , "GROUP_ID" VARCHAR(20)
    , "COLOR_ID" INT
    , "VALUE" VARCHAR(10)
    , "EXPLANATION" VARCHAR(100)
);


CREATE TABLE "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_QCAMS" (
      "ID" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 10)
    , "FIRST_NAME" VARCHAR(100)
    , "LAST_NAME" VARCHAR(100)
    , "EMAIL" VARCHAR(100)
);

CREATE TABLE "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_ALLOCATION" (
      "ID" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 10)
    , "QCAM_ID" INT
    , "GROUP_ID" VARCHAR(20)
);

-- VIEWS
DROP VIEW "CUSTOMER_ESCALATION_TRACKER"."MASTERDATA_SIDEBAR";
CREATE VIEW "CUSTOMER_ESCALATION_TRACKER"."MASTERDATA_SIDEBAR" AS (
	SELECT
      1 AS "ID"
    , 'Colors' as "NAME"
    , 'Review the color pallete available to the application' as "DESCRIPTION"
    , (SELECT COUNT(*) FROM "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_COLORS") AS "ENTRIES"
	FROM "DUMMY"
	UNION ALL
	SELECT
      2 AS "ID"
    , 'QCAMs' as "NAME"
    , 'Review and modify QCAMs, add or remove allocated customer groups to each' as "DESCRIPTION"
    , (SELECT COUNT(*) FROM "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_QCAMS") AS "ENTRIES"
	FROM "DUMMY"
	UNION ALL
	SELECT
      3 AS "ID"
    , 'Customer Escalation Levels' as "NAME"
    , 'Define and review customer escalation levels to be applied to new Escalations' as "DESCRIPTION"
    , (SELECT COUNT(*) FROM "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_QCAMS") AS "ENTRIES"
	FROM "DUMMY"
);
