SELECT * FROM "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_QCAMS";
SELECT * FROM "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_ALLOCATION";


-- VIEW ALL QCAMS
SELECT
      "QCAMS"."ID"
    , "QCAMS"."FIRST_NAME"
    , "QCAMS"."LAST_NAME"
    , COUNT("ALLOCATION"."GROUP_ID") AS "CUSTOMER_GROUPS"
FROM "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_QCAMS" AS "QCAMS"
    JOIN "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_ALLOCATION" AS "ALLOCATION"
    ON "QCAMS"."ID" = "ALLOCATION"."QCAM_ID"
WHERE 1 = 1
GROUP BY
      "QCAMS"."ID"
    , "QCAMS"."FIRST_NAME"
    , "QCAMS"."LAST_NAME"
ORDER BY "QCAMS"."ID";


-- VIEW ALL ALLOCATED GROUPS PER QCAM
SELECT
      "ALLOCATION"."GROUP_ID"
    , "CUSTOMERS"."GROUP_NAME"
FROM "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_ALLOCATION" AS "ALLOCATION"
    JOIN "CUSTOMER_ESCALATION_TRACKER"."CUSTOMERS" AS "CUSTOMERS"
    ON "ALLOCATION"."GROUP_ID" = "CUSTOMERS"."GROUP_ID"
WHERE 1 = 1
    AND "QCAM_ID" = 10
GROUP BY
      "ALLOCATION"."GROUP_ID"
    , "CUSTOMERS"."GROUP_NAME"
ORDER BY "ALLOCATION"."GROUP_ID";


-- dummy data
INSERT INTO "CUSTOMER_ESCALATION_TRACKER"."tblMasterData_QCAMS" (
    "FIRST_NAME", "LAST_NAME", "EMAIL"
) VALUES (
      'Emilian'
    , 'Neacsu'
    , 'emilian.neacsu@vitesco.com'
);
